Repository JasonPuglisi/descent, pull requests merged in 2024-07, with the labels that each got.

#166 Update dependencies
  gulpfile.js
  package.json
  views/template/external.pug
  yarn.lock
Labels: dependencies

#169 Run actions on pull requests
  .github/workflows/deploy-app-engine.yaml
Labels: bug

#167 feat: Add scrobble mode option
  README.md
  server.js
  source/js/config.js
  source/js/utility/metadata.js
  source/scss/config.scss
  views/config.pug
Labels: enhancement

#168 feat: Add keyboard shortcut to navigate to settings page
  source/js/utility/menu.js
Labels: enhancement
